class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'dl1'
        self.UnzipMirrorCommand = 'unzip1'
        self.TarMirrorCommand = 'tar1'
        self.CancelMirror = 'cnl1'
        self.CancelAllCommand = 'cnlall'
        self.ListCommand = 'srch1'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'hlp'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count'
        self.WatchCommand = 'ytdl1'
        self.TarWatchCommand = 'tarw1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage'

BotCommands = _BotCommands()
